### ISSUE TITLE
Missing Model Called "config"

### ISSUE THREAD

**Issue by ybx0000x0000xby** [MKMQ99/CARMN#1]
Dear Author:
In this project, it seems missing the modle called "config" 
![image](https://user-images.githubusercontent.com/91455962/134863452-b5adcc5d-3a4b-4c9d-9887-c8f2501f4f2b.png)

**Comment by ybx0000x0000xby** [comment]
And another problem is missing word embedding layer.(Maybe I not find it.)

**Comment by RebeII** [comment]
> And another problem is missing word embedding layer.(Maybe I not find it.)

I put word embedding in data preprocessing, so it's not here.

**Comment by RebeII** [comment]
> Dear Author: In this project, it seems missing the modle called "config"

The “config” file is just a few definitions of variables. The variables is easy to find and you can define it yourself.

**Comment by ybx0000x0000xby** [comment]
I see, thank you.
